[project]
name = "realtimetranslator-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "some-package>=0.1 ; sys_platform == 'linux'",
    "uvicorn[standard]>=0.37.0",
]

[tool.uv.workspace]
members = [
    "src/base_async",
    "src/base_async/src/base_module",
]

[tool.semantic_release]
version_variable = "pyproject.toml:project.version"
branch = "develop"
upload_to_pypi = false
upload_to_release = false
changelog_file = "CHANGELOG.md"
tag_format = "v{version}"
starting_version = "0.1.0"

[tool.semantic_release.branches.develop]
match = "develop"
prerelease = true
prerelease_token = "dev"
